workflow: update twister and doc build CI
Add apollo510b_evb to twister test
Add doc build to self-host, doc build cannot pass.

Signed-off-by: Swift Tian <swift.tian@ambiq.com>

diff --git a/.github/workflows/doc-build.yml b/.github/workflows/doc-build.yml
--- a/.github/workflows/doc-build.yml
+++ b/.github/workflows/doc-build.yml
@@ -4,34 +4,61 @@
 name: Documentation Build
 
 on:
-  schedule:
-  - cron: '0 */3 * * *'
-  push:
-    tags:
-    - v*
   workflow_dispatch:
+    inputs:
+      base:
+        description: 'Base branch name'
+        required: false
+  push:
+    branches:
+    - ambiq-stable
+  pull_request:
 
 
 permissions:
   contents: read
+  pull-requests: read
 
 env:
   DOXYGEN_VERSION: 1.14.0
   DOXYGEN_MD5SUM: e761a5097ae20ecccfd02041925f102a
-  JOB_COUNT: 8
+  JOB_COUNT: 12
 
 jobs:
   doc-file-check:
     name: Check for doc changes
-    runs-on: ubuntu-24.04
+    runs-on: [self-hosted, Linux, zephyr-ci]
     outputs:
       file_check: ${{ steps.check-doc-files.outputs.any_modified }}
+    if: github.event_name == 'pull_request'
     steps:
-    - name: checkout
-      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-      with:
-        ref: ${{ github.event.pull_request.head.sha }}
-        fetch-depth: 0
+    - name: Set event variables
+      id: set-vars
+      run: |
+        echo "BASE_REF=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
+
+    - name: Checkout
+      run: |
+        CACHE_DIR="/data/ambiqzephyrcache/zephyrproject/zephyr"
+        if [ -d "$GITHUB_WORKSPACE/zephyr/.git" ]; then
+          echo "Re‑using existing checkout, fetching ${GIT_REF}…"
+        elif [ -d "${CACHE_DIR}" ]; then
+          sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/*
+          echo "Cloning from local cache (${CACHE_DIR}) at ${GIT_REF}…"
+          git clone --reference "${CACHE_DIR}" \
+                    --depth 50 \
+                    https://github.com/${{ github.repository }}.git "zephyr"
+        else
+          sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/*
+          echo "Cache not found; doing fresh shallow clone at ${GIT_REF}…"
+          git clone --depth 50 \
+                    https://github.com/${{ github.repository }}.git "zephyr"
+        fi
+        cd "zephyr"
+        git fetch origin "${BASE_REF}"
+        git reset --hard "${BASE_REF}"
+        git clean -fdx
+
     - name: Check if Documentation related files changed
       uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
       id: check-doc-files
@@ -57,48 +84,62 @@ jobs:
     needs: [doc-file-check]
     if: >
       needs.doc-file-check.outputs.file_check == 'true' || github.event_name != 'pull_request'
-    runs-on:
-      group: zephyr-runner-v2-linux-x64-4xlarge
-    container:
-      image: ghcr.io/zephyrproject-rtos/ci-repo-cache:v0.28.6.20251003
-      options: '--entrypoint /bin/bash'
-    timeout-minutes: 20
+    runs-on: [self-hosted, Linux, zephyr-ci]
+    timeout-minutes: 90
     concurrency:
       group: doc-build-html-${{ github.ref }}
       cancel-in-progress: true
-    env:
-      BASE_REF: ${{ github.base_ref }}
-
-
     steps:
-
-    - name: Print cloud service information
+    - name: Set event variables
+      id: set-vars
       run: |
-        echo "ZEPHYR_RUNNER_CLOUD_PROVIDER = ${ZEPHYR_RUNNER_CLOUD_PROVIDER}"
-        echo "ZEPHYR_RUNNER_CLOUD_NODE = ${ZEPHYR_RUNNER_CLOUD_NODE}"
-        echo "ZEPHYR_RUNNER_CLOUD_POD = ${ZEPHYR_RUNNER_CLOUD_POD}"
-
-    - name: Apply container owner mismatch workaround
-      run: |
-        # FIXME: The owner UID of the GITHUB_WORKSPACE directory may not
-        #        match the container user UID because of the way GitHub
-        #        Actions runner is implemented. Remove this workaround when
-        #        GitHub comes up with a fundamental fix for this problem.
-        git config --global --add safe.directory ${GITHUB_WORKSPACE}
-
-    - name: Clone cached Zephyr repository
-      continue-on-error: true
-      run: |
-        git clone --shared /repo-cache/zephyrproject/zephyr .
-        git remote set-url origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
+        if [ "${{ github.event_name }}" = "pull_request" ]; then
+          echo "GIT_REF=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
+          echo "BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
+        else
+          echo "GIT_REF=${{ github.sha }}" >> $GITHUB_ENV
+          if [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event_name }}" = "schedule" ]; then
+            echo "BASE_REF=${{ github.event.inputs.base || github.event.repository.default_branch }}" >> $GITHUB_ENV
+          else
+            echo "BASE_REF=${{ github.event.before }}" >> $GITHUB_ENV
+          fi
+        fi
 
     - name: Checkout
-      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+      run: |
+        CACHE_DIR="/data/ambiqzephyrcache/zephyrproject/zephyr"
+        if [ -d "$GITHUB_WORKSPACE/zephyr/.git" ]; then
+          echo "Re‑using existing checkout, fetching ${GIT_REF}…"
+        elif [ -d "${CACHE_DIR}" ]; then
+          sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/*
+          echo "Cloning from local cache (${CACHE_DIR}) at ${GIT_REF}…"
+          git clone --reference "${CACHE_DIR}" \
+                    --depth 50 \
+                    https://github.com/${{ github.repository }}.git "zephyr"
+        else
+          sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/*
+          echo "Cache not found; doing fresh shallow clone at ${GIT_REF}…"
+          git clone --depth 50 \
+                    https://github.com/${{ github.repository }}.git "zephyr"
+        fi
+        cd "zephyr"
+        git fetch origin "${BASE_REF}"
+        git fetch origin "${GIT_REF}"
+        git reset --hard "${GIT_REF}"
+        git clean -fdx
+
+    - name: Set up Python
+      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
       with:
-        ref: ${{ github.event.pull_request.head.sha }}
-        fetch-depth: 0
+        python-version: 3.12
+
+    - name: Install Python packages
+      working-directory: zephyr
+      run: |
+        pip install -r doc/requirements.txt --require-hashes
 
     - name: Environment Setup
+      working-directory: zephyr
       run: |
         if [ "${{github.event_name}}" = "pull_request" ]; then
           git config --global user.email "bot@zephyrproject.org"
@@ -112,21 +153,19 @@ jobs:
         echo "$HOME/.local/bin" >> $GITHUB_PATH
         echo "$HOME/.cargo/bin" >> $GITHUB_PATH
 
-        west init -l . || true
+        CACHE_DEP="/data/ambiqzephyrcache/zephyrproject/"
+
+        if [ ! -d ../.west ]; then
+          west init -l .
+        fi
         west config manifest.group-filter -- +ci,+optional
         west config --global update.narrow true
-        west update --path-cache /repo-cache/zephyrproject 2>&1 1> west.update.log || west update --path-cache /repo-cache/zephyrproject 2>&1 1> west.update.log || ( rm -rf ../modules ../bootloader ../tools && west update --path-cache /repo-cache/zephyrproject)
+        west update --path-cache "${CACHE_DEP}" 2>&1 1> west.update.log || west update --path-cache "${CACHE_DEP}" 2>&1 1> west.update.log || ( rm -rf ../modules ../bootloader ../tools && west update --path-cache "${CACHE_DEP}")
         west forall -c 'git reset --hard HEAD'
-
-        echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$( cat SDK_VERSION )" >> $GITHUB_ENV
-
-    - name: Install Python packages required for documentation build
-      run: |
-        pip install -r scripts/requirements-actions.txt --require-hashes
-        pip install -r doc/requirements.txt --require-hashes
 
     - name: Build HTML documentation
       shell: bash
+      working-directory: zephyr
       run: |
         if [[ "$GITHUB_REF" =~ "refs/tags/v" ]]; then
           DOC_TAG="release"
@@ -143,7 +182,7 @@ jobs:
         DOC_TAG=${DOC_TAG} \
         SPHINXOPTS="-j ${JOB_COUNT} -W --keep-going -T" \
         SPHINXOPTS_EXTRA="-q -t publish" \
-        make -C doc ${DOC_TARGET}
+        make -C doc ${DOC_TARGET} -j 12
 
         # API documentation coverage
         python3 -m coverxygen --xml-dir  doc/_build/html/doxygen/xml/ --src-dir include/ --output doc-coverage.info
@@ -152,22 +191,23 @@ jobs:
         genhtml --no-function-coverage --no-branch-coverage new.info -o coverage-report
 
     - name: Compress documentation build artifacts
+      working-directory: zephyr
       run: |
         tar --use-compress-program="xz -T0" -cf html-output.tar.xz --exclude html/_sources --exclude html/doxygen/xml --directory=doc/_build html
         tar --use-compress-program="xz -T0" -cf api-output.tar.xz --directory=doc/_build html/doxygen/html
         tar --use-compress-program="xz -T0" -cf api-coverage.tar.xz coverage-report
 
     - name: Upload HTML output
-      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
       with:
         name: html-output
-        path: html-output.tar.xz
+        path: zephyr/html-output.tar.xz
 
     - name: Upload Doxygen coverage artifacts
-      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
       with:
         name: api-coverage
-        path: api-coverage.tar.xz
+        path: zephyr/api-coverage.tar.xz
 
 
     - name: Summarize PR documentation URLs
@@ -185,7 +225,7 @@ jobs:
         echo "API Coverage Report will be available shortly at: ${API_COVERAGE_URL}" >> $GITHUB_STEP_SUMMARY
 
     - name: Upload PR number
-      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
       if: github.event_name == 'pull_request'
       with:
         name: pr_num
@@ -196,24 +236,49 @@ jobs:
     needs: [doc-file-check]
     if: |
       github.event_name != 'pull_request'
-    runs-on: ubuntu-24.04
+    runs-on: [self-hosted, Linux, zephyr-ci]
     timeout-minutes: 120
     concurrency:
       group: doc-build-pdf-${{ github.ref }}
       cancel-in-progress: true
 
     steps:
-    - name: checkout
-      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-      with:
-        path: zephyr
+    - name: Set event variables
+      id: set-vars
+      run: |
+        echo "BASE_REF=${{ github.event.inputs.base || github.event.repository.default_branch }}" >> $GITHUB_ENV
+
+    - name: Checkout
+      run: |
+        CACHE_DIR="/data/ambiqzephyrcache/zephyrproject/zephyr"
+        if [ -d "$GITHUB_WORKSPACE/zephyr/.git" ]; then
+          echo "Re‑using existing checkout, fetching ${GIT_REF}…"
+        elif [ -d "${CACHE_DIR}" ]; then
+          sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/*
+          echo "Cloning from local cache (${CACHE_DIR}) at ${GIT_REF}…"
+          git clone --reference "${CACHE_DIR}" \
+                    --depth 50 \
+                    https://github.com/${{ github.repository }}.git "zephyr"
+        else
+          sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/*
+          echo "Cache not found; doing fresh shallow clone at ${GIT_REF}…"
+          git clone --depth 50 \
+                    https://github.com/${{ github.repository }}.git "zephyr"
+        fi
+        cd "zephyr"
+        git fetch origin "${BASE_REF}"
+        git reset --hard "${BASE_REF}"
+        git clean -fdx
 
     - name: Set up Python
-      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
+      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
       with:
         python-version: 3.12
-        cache: pip
-        cache-dependency-path: doc/requirements.txt
+
+    - name: Install Python packages
+      working-directory: zephyr
+      run: |
+        pip install -r doc/requirements.txt --require-hashes
 
     - name: install-pkgs
       run: |
@@ -231,18 +296,6 @@ jobs:
         sudo tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz -C /opt
         echo "/opt/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH
 
-    - name: Setup Zephyr project
-      uses: zephyrproject-rtos/action-zephyr-setup@c125c5ebeeadbd727fa740b407f862734af1e52a # v1.0.9
-      with:
-        app-path: zephyr
-        toolchains: 'arm-zephyr-eabi'
-        enable-ccache: false
-
-    - name: install-pip-pkgs
-      working-directory: zephyr
-      run: |
-        pip install -r doc/requirements.txt --require-hashes
-
     - name: build-docs
       shell: bash
       working-directory: zephyr
@@ -257,11 +310,11 @@ jobs:
         DOC_TAG=${DOC_TAG} \
         SPHINXOPTS="-q -j ${JOB_COUNT}" \
         LATEXMKOPTS="-quiet -halt-on-error" \
-        make -C doc pdf
+        make -C doc pdf -j 12
 
     - name: upload-build
       if: always()
-      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
       with:
         name: pdf-output
         if-no-files-found: ignore
